### ISSUE TITLE
Unify supported schemas with TypeSchema?

### ISSUE THREAD

**Issue by ciscoheat** [gcornut/valibot-json-schema#6]
[TypeSchema](https://github.com/decs/typeschema) is a nice project that unifies a range of validation libraries, including valibot. 

I noticed that it's using a different "supported schemas" type than you do with this library. Here's their definition: https://github.com/decs/typeschema/blob/main/src/adapters/valibot.ts#L9

I had some trouble unifying this with your [SupportedSchemas](https://github.com/gcornut/valibot-json-schema/blob/main/src/toJSONSchema/schemas.ts#L31C13-L31C29) type. Maybe you know better what BaseSchema does, and if it's a good idea to add it, to make it work with both libraries.

**Comment by gcornut** [comment]
Yes `BaseSchema` is the generic definition of a valibot schema while my `SupportedSchema` type is explicit on what schemas are supported or not. 

I guess we can use `BaseSchema` for the on the `toJSONSchema()` input options and keep the `SupportedSchema` for internal documentation. 

The only downside is that calling with a known unsupported schema (like: `toJSONSchema({ schema: nan() })`) won't produce a type error but a runtime error. But it's not that useful because it does not work with nested schema that contain an unsupported schema (like: `toJSONSchema({ schema: object({ prop: nan() }) })` .

If you want to open a PR, go ahead

**Comment by ciscoheat** [comment]
I'll do that, thanks. Will it be ok adding the async version as well?

**Comment by gcornut** [comment]
I never tested the conversion of async schema. It should work because async and sync schema have the same options.

I guess we can still say we accept `BaseSchemaAsync` but in practice I think async schema are useless without `customAsync()` and of course it's impossible to convert to JSON schema

**Comment by gcornut** [comment]
Merged and released in v0.0.22
